#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    # 配置文件改为 /usr/bin/frpc.ini
    procd_set_param command /usr/bin/frpc -c /usr/bin/frpc.ini
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param file /var/log/frpc.log
    # 进程崩溃自动重启
    procd_set_param respawn
    procd_set_param respawn_delay 5
    procd_close_instance
}

stop_service() {
    killall frpc
}