# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: Auto-Clean

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */6 * *'

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: 清理Action运行记录，Release与标签完全保留
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          delete_releases: false
          delete_tags: false
          delete_workflows: true
          # 每个工作流单独保留最新5条运行记录
          workflows_keep_count: 5
