      - name: 拉取仓库配置文件
        uses: actions/checkout@v6

      # =========新增这段==========
      - name: 安装OpenWrt编译依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses-dev gawk flex bison quilt libssl-dev xsltproc libxml2-utils
      # ==========================

      - name: 清理本地缓存
        if: github.event.inputs.clean_cache == 'true'
        run: |
          rm -rf openwrt .ccache build.log upstream_commit.txt last_commit.txt pkg_ref.txt || true
          echo "✅ 缓存清理完成"
